version: "3.8"

services:
  # redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  # fast api
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

    environment:
      - REDIS_HOST=redis

    env_file:
      - .env

    depends_on:
      - redis

    volumes:
      - .:/app

  #ngrok service
  ngrok:
    image: ngrok/ngrok:latest

    ports:
      - "4040:4040"

    command: http api:8000

    env_file:
      - .env

    depends_on:
      - api

  # orchestrator agent
  orchestrator:
    build: .

    command: python -u -m app.services.orchestrator.exec_file

    environment:
      - REDIS_HOST=redis

    env_file:
      - .env

    depends_on:
      - redis
    volumes:
      - .:/app
